// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT4TSZmLuyuMRekukHXdTHsjyp9QJ4Dtk',
    appId: '1:1020577643728:android:d9d8d6b3520b1b6dd7b2d5',
    messagingSenderId: '1020577643728',
    projectId: 'fir-test-e64ea',
    databaseURL: 'https://fir-test-e64ea-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-e64ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtt48mUdmDPlaJw2qS4mTPvRJgN4Geovw',
    appId: '1:1020577643728:ios:13baa4976df15700d7b2d5',
    messagingSenderId: '1020577643728',
    projectId: 'fir-test-e64ea',
    databaseURL: 'https://fir-test-e64ea-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-e64ea.appspot.com',
    androidClientId: '1020577643728-0n6lhg5dj36tcvq0c3ja67crocjsouup.apps.googleusercontent.com',
    iosClientId: '1020577643728-43nci791kpod1bd5anmjrib59tn0q77b.apps.googleusercontent.com',
    iosBundleId: 'com.example.second',
  );
}
